# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HSLU_HS25_DSPRO1',
                'doc_host': 'https://theodorahaimoff.github.io',
                'git_url': 'https://github.com/theodorahaimoff/HSLU_HS25_DSPRO1',
                'lib_path': 'HSLU_HS25_DSPRO1'},
  'syms': {'HSLU_HS25_DSPRO1.core': {'HSLU_HS25_DSPRO1.core.foo': ('core.html#foo', 'HSLU_HS25_DSPRO1/core.py')}}}
